### ISSUE TITLE
the images < 1 > go in wrong direction

### ISSUE THREAD

**Issue by alexlib** [OpenPIV/openpiv_gui#28]
@royekorolik  Using the button at the bottom to move left/right with the images (forward, backward) it seems that we go in the wrong direction. if you see in the directory the flow rotates clockwise between image 359 to 362. when i do 1> 2> 3 >4 I see counterclockwise rotation. 

Thanks

**Comment by royekorolik** [comment]
its because i made it so it wouldnt use the piv on the last and first image and just added the piv from the other image. i can take it down or just do the piv on the last image with the first one.

**Comment by alexlib** [comment]
I do not understand how the < > buttons are related to PIV processing? These are just for going through the images to see the "motion". Can you please explain it by a link to the code which is relevant, so I can understand why it's there?

**Comment by alexlib** [comment]
I expect when I press button > to go from 1 to 2, 2 to 3 and so on when I reach the end I'd like to have this button stopped and only a button to the left < is active until I get back to 1.
