### ISSUE TITLE
post panel visual tiny things

### ISSUE THREAD

**Issue by alexlib** [OpenPIV/openpiv_gui#29]
![image](https://user-images.githubusercontent.com/747110/52168686-a6668f80-2735-11e9-96ea-3fad6aa09dd7.png)

**Comment by alexlib** [comment]
please make it visible

**Comment by royekorolik** [comment]
is this Still a problem and if it is can i have a new image to see if it changed

**Comment by alexlib** [comment]
it is good now. close it
