### ISSUE TITLE
what is this part doing? 

### ISSUE THREAD

**Issue by alexlib** [OpenPIV/openpiv_gui#32]
@royekorolik could you help me to understand what do we do with this part? 

```
            for j in range(0, 4):
                for k in range(len(res_list[j])):
                    data[k][j] = res_list[j][k]
            self.piv.piv_images_list[i][4] = data
```

**Comment by royekorolik** [comment]
its for saving the data for when you want to save it i forgot to use # because its still not in use

**Comment by royekorolik** [comment]
its for putting the data of the piv in a numpy array so it will work on the openpiv_savevec.py i forgot to put # because its no in use now

**Comment by alexlib** [comment]
+1
